import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import sortiva from 'eslint-plugin-sortiva'

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'tmp/**',
      'docs/**',
      // Generated by `next build`; its triple-slash references are Next's, not ours.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.node },
    },
    plugins: { sortiva },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',

      // Invariant 25 — one instrumented wrapper per vendor SDK.
      'sortiva/no-direct-provider-sdk': 'error',

      // Invariant 25, for the vendor with no SDK to ban: DataForSEO is a plain
      // HTTPS endpoint, so the host string itself is what has to be fenced in.
      'sortiva/no-direct-vendor-http': 'error',

      // Invariant 9 — every threshold number lives in packages/rules.
      'sortiva/no-threshold-literals': 'error',

      // No code outside packages/db
      // may import a raw table or the raw database handle, so no query can
      // reach a table without naming the account whose data it touches.
      // Audit T0.3 [major]; remediation D5 (stopgap half).
      'sortiva/no-raw-db-access': 'error',
    },
  },

  // The rule that bans a vendor host has to name that host, and the test that
  // proves the rule works has to plant it. Those two files are the definition
  // and the proof, not a call site.
  {
    files: [
      'tools/eslint-plugin-sortiva/rules/no-direct-vendor-http.js',
      'scripts/prove-lint.mjs',
      // The planted violations themselves. Each case file exists to contain the
      // thing the rule bans; that is the whole point of it.
      'scripts/lint-proofs/**',
    ],
    rules: { 'sortiva/no-direct-vendor-http': 'off' },
  },

  // packages/rules is the one place threshold numbers are allowed to be compared.
  {
    files: ['packages/rules/**/*.{ts,tsx,js,mjs}'],
    rules: { 'sortiva/no-threshold-literals': 'off' },
  },

  // Tests and fixtures assert against concrete numbers by definition; the rule
  // exists to stop *production* code carrying thresholds, not to stop tests
  // proving that packages/rules serves the right ones.
  {
    files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', '**/fixtures/**', '**/__fixtures__/**'],
    rules: { 'sortiva/no-threshold-literals': 'off' },
  },

  // The bounded D5 exemption. `job_steps`, `ingestion_jobs`, `job_dlq` and
  // `idempotency_ledger` have no scoped repositories to call: `job_steps` has no
  // account_id column of its own (it hangs off ingestion_jobs), the ledger
  // deliberately has none at all so an account cascade cannot erase the record
  // that paid work was done, and supplying the helpers means editing packages/db, which
  // neither R1 nor R3 owns. These three files are the whole exemption; it is
  // named function-by-function in DECISIONS 2026-08-31 R1 and 2026-08-31 R3, and
  // ends when the durable D5 card lands.
  {
    files: [
      'packages/jobs/src/runtime/steps.ts',
      'packages/jobs/src/runtime/dlq.ts',
      'packages/jobs/src/runtime/ledger.ts',
    ],
    rules: { 'sortiva/no-raw-db-access': 'off' },
  },

  // Lane A's database code, which is a repository layer living in the wrong
  // directory. Every one of these files does name the account it acts for —
  // they take an AccountScope, filter on accountId, or are legitimately
  // system-scoped (the preview cache precedes any account, and the domain claim
  // must look across accounts, since asking "does anyone hold this?" is the
  // whole point of a claim). They sit in apps/web only because packages/db was
  // held by another session throughout wave 1, which each card journalled at the
  // time rather than working around silently.
  //
  // This is a location problem, not a scoping hole, and it is the durable half
  // of remediation D5. The exemption ends when that card moves these into
  // packages/db as scoped repositories. Do not add to this list: a new file that
  // needs it belongs in packages/db in the first place.
  {
    files: [
      'apps/web/app/api/account/_lib/load.ts',
      'apps/web/app/api/auth/_lib/provisioning.ts',
      'apps/web/app/api/billing/_lib/handlers.ts',
      'apps/web/app/api/billing/_lib/store.ts',
      'apps/web/app/api/domain/_lib/store.ts',
      'apps/web/app/api/preview/_lib/config.ts',
      'apps/web/app/api/preview/_lib/store.ts',
    ],
    rules: { 'sortiva/no-raw-db-access': 'off' },
  },

  // A composition root, not a query. This file never reads a table: it takes the
  // shared connection pool and hands it to the billing store, which is what makes
  // the per-account lock engage in production — before that, the lock ran only in
  // tests, the one place it was not needed. Naming concrete infrastructure is what
  // a composition root is for; the rule cannot tell "supplies a pool" from "queries
  // with one", so the distinction is recorded here instead.
  //
  // The durable version moves this construction into `apps/web/instrumentation.ts`,
  // the process's actual composition root, and passes the pool down. That is a
  // refactor, not a fix, and it belongs with the D5 card.
  {
    files: [
      'apps/web/app/api/webhooks/stripe/_lib/receiver.ts',
      // The process's actual composition root, which the note above names as
      // where this construction eventually belongs. It reads no table: it hands
      // the database factory to the spend-cap sweep's task registration, the
      // way it already hands the analytics client to the worker. A background
      // job cannot be given its database by a request, so somebody at the top
      // has to name it.
      'apps/web/instrumentation.ts',
    ],
    rules: { 'sortiva/no-raw-db-access': 'off' },
  },

  // Integration tests set up and inspect rows directly; the rule exists to stop
  // *production* code reaching a table without an account, not to stop a test
  // asserting on what the repositories wrote.
  {
    files: [
      '**/*.test.{ts,tsx}',
      '**/*.spec.{ts,tsx}',
      '**/testing.ts',
      '**/fixtures/**',
      // The chaos scenarios are test code that has to set up and
      // inspect rows a repository does not expose.
      'packages/jobs/src/chaos/**',
    ],
    rules: { 'sortiva/no-raw-db-access': 'off' },
  },

  // CLAUDE.md: route handlers parse -> call core -> serialise.
  {
    files: ['apps/web/app/api/**/route.{ts,tsx}'],
    rules: { 'sortiva/route-handler-imports': 'error' },
  },

  {
    files: ['**/*.{jsx,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
  },

  {
    files: ['scripts/**/*.mjs', 'tools/**/*.js', '*.config.{js,mjs,ts}'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' },
  },
)
