import js from '@eslint/js'
import globals from 'globals'
import tseslint from 'typescript-eslint'
import sortiva from 'eslint-plugin-sortiva'

export default tseslint.config(
  {
    ignores: [
      '**/node_modules/**',
      '**/dist/**',
      '**/.next/**',
      '**/coverage/**',
      'tmp/**',
      'docs/**',
      // Generated by `next build`; its triple-slash references are Next's, not ours.
      '**/next-env.d.ts',
    ],
  },

  js.configs.recommended,
  ...tseslint.configs.recommended,

  {
    languageOptions: {
      ecmaVersion: 2023,
      sourceType: 'module',
      globals: { ...globals.node },
    },
    plugins: { sortiva },
    rules: {
      '@typescript-eslint/no-unused-vars': [
        'error',
        { argsIgnorePattern: '^_', varsIgnorePattern: '^_' },
      ],
      '@typescript-eslint/no-explicit-any': 'warn',

      // Invariant 25 — one instrumented wrapper per vendor SDK.
      'sortiva/no-direct-provider-sdk': 'error',

      // Invariant 9 — every threshold number lives in packages/rules.
      'sortiva/no-threshold-literals': 'error',

      // CLAUDE.md code-structure rules / tech §3 — no code outside packages/db
      // may import a raw table or the raw database handle, so no query can
      // reach a table without naming the account whose data it touches.
      // Audit T0.3 [major]; remediation D5 (stopgap half).
      'sortiva/no-raw-db-access': 'error',
    },
  },

  // packages/rules is the one place threshold numbers are allowed to be compared.
  {
    files: ['packages/rules/**/*.{ts,tsx,js,mjs}'],
    rules: { 'sortiva/no-threshold-literals': 'off' },
  },

  // Tests and fixtures assert against concrete numbers by definition; the rule
  // exists to stop *production* code carrying thresholds, not to stop tests
  // proving that packages/rules serves the right ones.
  {
    files: ['**/*.test.{ts,tsx}', '**/*.spec.{ts,tsx}', '**/fixtures/**', '**/__fixtures__/**'],
    rules: { 'sortiva/no-threshold-literals': 'off' },
  },

  // The bounded D5 exemption. `job_steps`, `ingestion_jobs` and `job_dlq` have
  // no scoped repositories to call: `job_steps` has no account_id column of its
  // own (main §13 hangs it off ingestion_jobs), and supplying the join-scoped
  // helpers means editing packages/db, which card R1 does not own. These two
  // files are the whole exemption; it is named function-by-function in
  // DECISIONS 2026-08-31 R1 and ends when the durable D5 card lands.
  {
    files: ['packages/jobs/src/runtime/steps.ts', 'packages/jobs/src/runtime/dlq.ts'],
    rules: { 'sortiva/no-raw-db-access': 'off' },
  },

  // Integration tests set up and inspect rows directly; the rule exists to stop
  // *production* code reaching a table without an account, not to stop a test
  // asserting on what the repositories wrote.
  {
    files: [
      '**/*.test.{ts,tsx}',
      '**/*.spec.{ts,tsx}',
      '**/testing.ts',
      '**/fixtures/**',
      // The chaos scenarios (main §14.3.9) are test code that has to set up and
      // inspect rows a repository does not expose.
      'packages/jobs/src/chaos/**',
    ],
    rules: { 'sortiva/no-raw-db-access': 'off' },
  },

  // CLAUDE.md: route handlers parse -> call core -> serialise.
  {
    files: ['apps/web/app/api/**/route.{ts,tsx}'],
    rules: { 'sortiva/route-handler-imports': 'error' },
  },

  {
    files: ['**/*.{jsx,tsx}'],
    languageOptions: { globals: { ...globals.browser } },
  },

  {
    files: ['scripts/**/*.mjs', 'tools/**/*.js', '*.config.{js,mjs,ts}'],
    rules: { '@typescript-eslint/no-unused-vars': 'off' },
  },
)
