'use client'

import { useState } from 'react'
import { t as defaultTranslate, type Translate } from '../strings'
import {
  CompetitorsSection,
  FamiliesSection,
  KeywordsSection,
  RichnessSection,
  SearchConsoleStatusSection,
  TopProductsSection,
} from './ConfirmationSections'
import { isConfirmable, type ProfileDraft } from './confirmation'

/**
 * The last screen before anything is written: everything we worked out about a
 * store, laid out to be corrected.
 *
 * Nothing generated by ingestion is treated as true until this is confirmed.
 * That is the point of the screen — the persona, the best sellers, the search
 * terms and the competitors all feed every decision the product makes
 * afterwards, and a wrong one is expensive and slow to notice. So each section
 * is editable in place, and the button that ends onboarding stays out of reach
 * until the fields every later step depends on actually hold something.
 *
 * After confirmation this same screen becomes Settings → Store profile, which
 * is why every section is a component rather than markup in a page.
 */

export interface ConfirmationReviewProps {
  readonly profile: ProfileDraft
  readonly t?: Translate
  readonly confirmEndpoint?: string
  /** Called once the profile is confirmed and the first scan has been started. */
  readonly onConfirmed?: () => void
}

export function ConfirmationReview({
  profile,
  t = defaultTranslate,
  confirmEndpoint = '/api/profile/confirm',
  onConfirmed,
}: ConfirmationReviewProps) {
  const [description, setDescription] = useState(profile.description)
  const [language, setLanguage] = useState(profile.language)
  const [country, setCountry] = useState(profile.country)
  const [audience, setAudience] = useState(profile.audience)
  const [tone, setTone] = useState(profile.tone)
  const [products, setProducts] = useState(profile.topProducts)
  const [keywords, setKeywords] = useState(profile.keywords)
  const [competitors, setCompetitors] = useState(profile.competitors)
  const [submitting, setSubmitting] = useState(false)
  const [error, setError] = useState<'failed' | 'already_confirmed' | null>(null)

  const valid = isConfirmable({ description, language, country })

  async function confirm() {
    if (!valid || submitting) return
    setSubmitting(true)
    setError(null)
    try {
      const response = await fetch(confirmEndpoint, {
        method: 'POST',
        headers: { 'content-type': 'application/json' },
        body: JSON.stringify({
          description,
          language,
          country,
          audience,
          tone,
          // The order of this list is the edit: it is what the ranking means.
          topProductIds: products.map((product) => product.id),
        }),
      })

      if (response.ok) {
        onConfirmed?.()
        return
      }
      setError(response.status === 409 ? 'already_confirmed' : 'failed')
    } catch {
      setError('failed')
    } finally {
      setSubmitting(false)
    }
  }

  return (
    <div className="sortiva-confirm" data-confirm-sections="7">
      <header className="sortiva-confirm__header">
        <h1 className="sortiva-onboarding-card__heading">{t('confirm.heading')}</h1>
        <p className="sortiva-onboarding-card__body">{t('confirm.body')}</p>
      </header>

      <section className="sortiva-confirm__section" data-confirm-section="business_profile">
        <h2 className="sortiva-confirm__section-heading">{t('confirm.business.heading')}</h2>

        <label htmlFor="sortiva-profile-description">{t('confirm.business.description')}</label>
        <textarea
          id="sortiva-profile-description"
          value={description}
          onChange={(event) => setDescription(event.target.value)}
        />

        <div className="sortiva-confirm__pair">
          <div>
            <label htmlFor="sortiva-profile-language">{t('confirm.business.language')}</label>
            <input
              id="sortiva-profile-language"
              value={language}
              maxLength={5}
              onChange={(event) => setLanguage(event.target.value)}
            />
            <p className="sortiva-confirm__section-note">{t('confirm.business.languageHint')}</p>
          </div>
          <div>
            <label htmlFor="sortiva-profile-country">{t('confirm.business.country')}</label>
            <input
              id="sortiva-profile-country"
              value={country}
              maxLength={2}
              onChange={(event) => setCountry(event.target.value.toUpperCase())}
            />
            <p className="sortiva-confirm__section-note">{t('confirm.business.countryHint')}</p>
          </div>
        </div>

        <div className="sortiva-confirm__pair">
          <div>
            <label htmlFor="sortiva-profile-audience">{t('confirm.business.audience')}</label>
            <input
              id="sortiva-profile-audience"
              value={audience}
              onChange={(event) => setAudience(event.target.value)}
            />
          </div>
          <div>
            <label htmlFor="sortiva-profile-tone">{t('confirm.business.tone')}</label>
            <input
              id="sortiva-profile-tone"
              value={tone}
              onChange={(event) => setTone(event.target.value)}
            />
          </div>
        </div>
      </section>

      <TopProductsSection products={products} onChange={setProducts} t={t} />
      <KeywordsSection keywords={keywords} onChange={setKeywords} t={t} />
      <CompetitorsSection
        competitors={competitors}
        suggestions={profile.competitorSuggestions}
        onChange={setCompetitors}
        t={t}
      />
      <FamiliesSection families={profile.families} t={t} />
      <RichnessSection richness={profile.richness} t={t} />
      <SearchConsoleStatusSection searchConsole={profile.searchConsole} t={t} />

      <section className="sortiva-confirm__section" data-confirm-section="closing">
        <h2 className="sortiva-confirm__section-heading">{t('confirm.closing.heading')}</h2>
        <p className="sortiva-confirm__section-body">{t('confirm.closing.body')}</p>
      </section>

      <div className="sortiva-confirm__footer" role="group" aria-label={t('confirm.footer.label')}>
        {error ? (
          <p className="sortiva-confirm__error" role="alert">
            {error === 'already_confirmed' ? t('confirm.alreadyConfirmed') : t('confirm.failed')}
          </p>
        ) : null}
        <button
          type="button"
          className="sortiva-onboarding-card__primary"
          onClick={confirm}
          disabled={!valid || submitting}
        >
          {t('confirm.submit')}
        </button>
      </div>
    </div>
  )
}
